### PR TITLE
extract_patches_min

### PR DESCRIPTION
**Pull request by MartinRoth**
Dear Simon and Antoine,

thank you very much for your nice work! I am using imager amongst others to obtain a DarkChannelPrior (based on [https://github.com/sjtrny/Dark-Channel-Haze-Removal ].) Using extract_patches_min instead of doing the min calculation in R increases the speed substantially. It might be interesting for other people as well, what do you think?

Cheers,
Martin

PS: It might be also good to introduce some testing :)

### CODE REVIEW

**Comment by dahtah** [comment]
Dear Martin, 

Thank you for your contribution, I like the idea. I went ahead and generalised it a bit using a very neat hidden feature of CImg, which is its byte-compiled DSL (its "math parser"). So now we have a patch_summary function, which extracts one-dimensional summaries from image patches. 
I put it in the development branch, so if you try
``` install_github("dahtah/imager",ref="cxxplugin") ```
you should find there's a new function called patch_summary, taking a CImg expression as input. 

The DSL is documented [here](http://gmic.eu/reference.shtml) (see section on mathematical expressions). 

Here's how to use it:

```
tst = grayscale(boats)
#In the DSL, "ia" is the image mean and "ic" is the image median
patch_summary(tst,"ia",100,100,10,10) #Patch mean
patch_summary(tst,"ic",100,100,10,10) #Patch median
patch_summary(tst,"(ic-ia)/ia",100,100,10,10) #(median -mean)/mean 
patch_summary(tst,"im",100,100,10,10) #minimum
patch_summary(tst,"iM-im",100,100,10,10) #range (max - min)

#Here's an implementation of median filtering
patches <- pixel.grid(tst)  %>% mutate(w=3,h=3) #Patch at every pixel
out <- mutate(patches,med=patch_summary(tst,"ic",x,y,w,h))
as.cimg(out,v.name="med") %>% plot
```

I still need to test it and document it better, but what do you think? What's also neat is that the current dev. version of imager supports OpenMP, so we can parallelise that stuff easily.
NB: There's also some issues with 0-indexing (C++) vs 1-indexing (R) that I need to fix.

**Comment by MartinRoth** [comment]
Dear Simon,

thanks for the fast reply. I like the generalization (and the new name) a
lot. However, I did a microbenchmark for comparison and it turned out that
that it is slower roughly by a factor of two:

#Unit: microseconds
#
expr     min       lq      mean  median       uq  max
neval
# extract_patches_min(boats, 150:250, 100:200, rep(15, 101), rep(15, 101))
606.381 636.9145  698.5497 655.040  732.851 1165.821   100
# patch_summary(boats, "im", 150:250, 100:200, rep(15, 101), rep(15, 101))
946.675 973.2310 1072.6838 998.846 1137.582 1680.364   100

I am not sure of the reason, but could it be that the expression should be
parsed only one time in the beginning? (Why does the compiler not take care
of this?) Unfortunately, I do not how to test this (only limited c++
experience so far).

Best wishes,
Martin

**Comment by dahtah** [comment]
OK, what about a patch_summary that recognises "min", "max", "median" and such as special cases and calls specialised routines? 
I'm going to get in touch with CImg's author and ask if we can have precompiled expressions.
Side-note: the morphology operations can be used to compute local minima/maxima, e.g. 
``` erode_square(im,4,4) ```
computes the minimum of the pixels in a 4x4 window.  You can take minima first and extract patches later, rather than the other way around.

**Comment by dahtah** [comment]
Hi Martin. There's a new function in the master branch called "patchstat", which should do what you need (it recognises a few function like "min","max" and "median", and calls specialised routines).
``` patchstat(boats,"median",c(10,20),c(15,5),2,2) ```
Let me know if that does the job for you.

**Comment by MartinRoth** [comment]
Dear Simon,

sorry for the delay. I tested the function (in comparison with the one I
proposed - which gives the same result as min(extract_patches(...)) and
obtained strange results:

--
system.time(test1 <- extract_patches_min(boats, 150 : 250, 100 : 200,
rep(15, 101), rep(15, 101))) # from the pull request
system.time(test2 <- patchstat(boats, "min", 150 : 250, 100 : 200, rep(15,
101), rep(15, 101)))

test1 - test2
  [1]   0.00000000  -0.22083567  -1.28004956   0.00000000  -0.07508495
-1.38103399  -2.27493624   0.00000000  -0.41135267   0.00000000
 [11]   0.36147308 -80.69402155  -6.30172795  -5.68241491  -0.44167134
0.00000000   0.00000000   0.00000000   0.00000000   0.00000000
 [21]   0.00000000   0.00000000   0.00000000   0.00000000   0.00000000
0.00000000  36.90252782   8.88562308  31.71060155  14.14874626
 [31]   7.87346303   4.98589937   2.41558775   2.37944756   0.00000000
0.03877478   5.74763441  -1.52468125  -0.16797443  -3.71359771
 [41]  -0.28850568  -2.34525494  -2.45489367  -5.19650843  -5.38103393
-6.41769114  -4.06398009  -2.46545324  -1.04776202   0.00000000
 [51]   0.00000000  -2.11720251   0.00000000   0.00000000  -0.86235832
-0.60486542  -2.53876770  -0.51533286   0.00000000   0.00000000
 [61]  -6.41894459 -61.23156432  -5.95435543  -0.86869688   0.00000000
-0.13641641  -0.05410060  -0.29926343  -0.21906517  -0.78093481
 [71]  -0.13764166   0.00000000   0.00000000   0.00000000  -0.30225918
0.00000000   0.00000000   0.00000000   0.00000000   0.30225918
 [81]   0.00000000   0.00000000   0.00000000   0.13764166   0.24339234
0.00000000  -0.15985128   0.00000000  -0.64064445   0.00000000
 [91]   0.00000000   0.00000000   0.00000000   0.00000000   0.00000000
0.00000000   0.00000000 -15.86199695  -4.95981580   0.00000000
[101]   0.00000000
--

Often the values are the same, but they can deviate considerably. I thought
maybe the issue is with the boundaries of the patches (you give a warning
in the description), so I changed the x-values to 100 : 200, but this did
not resolve the issue.

Do you have an explanation for the different results?

Cheers,
Martin

**Comment by dahtah** [comment]
Dear Martin, 

No time to check this now but I think it's just that your C++ code uses 0-based indexing, whereas in R it's 1-based. So a patch at (x,y) in C is at (x+1,y+1) in R. Would that explain it?

**Comment by MartinRoth** [comment]
Indeed it does, so I am happy to use patchstat from now on :)

**Pull request closed without merging**
