### PR TITLE
Used ffmpeg conversion feature to directly load a video into R

### LINKED ISSUE #65: Cannot load video with spaces in the filename

### LINKED ISSUE #66: Faster video loading without saving temporary files

### PR DESCRIPTION
**Pull request by seblamydlc**
Implemented a way to load video that doesn't need to write temporary files on the disk. Fixed loading filename with spaces. fixes #65 fixes #66

### CODE REVIEW

**Comment by dahtah** [comment]
Many thanks for contributing, looks good! Which platform have you tested this on?

**Comment by seblamydlc** [comment]
Thanks. I tested it on Linux only (Ubuntu server 14.04).

**Comment by dahtah** [comment]
There's a problem with the "%p%" operator being undefined (in video.information) - I imagine it's paste? 
I can test this on a Windows virtual machine, but I've got no easy access to a Mac, do you?

**Comment by seblamydlc** [comment]
Oh sorry I didn't even see we left that in there. Indeed it's a handy shortcut to paste.
I can test it on a Mac yes.

**Comment by seblamydlc** [comment]
Tested on a Mac and it worked

**Comment by dahtah** [comment]
I've just tested it on Linux and it works great! You're missing a header on Windows, though: 

```
d:/Compiler/gcc-4.9.3/mingw_32/bin/g++  -std=gnu++11 -I"D:/RCompile/recent/R/include" -DNDEBUG -I../inst/include -DSTRICT_R_HEADERS -Dcimg_use_r -DCIMG_COMPILING -Dcimg_use_fftw3_singlethread -Dcimg_use_tiff  -Dcimg_use_rng -Dcimg_verbosity=1 -fpermissive -Id:/Rcompile/CRANpkg/extralibs215/local215/include -Id:/Rcompile/CRANpkg/extralibs215/local215/include -fopenmp -I"d:/RCompile/CRANguest/R-devel/lib/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c video_io.cpp -o video_io.o
video_io.cpp: In function 'SEXPREC* read_video(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)':
video_io.cpp:34:45: error: expected primary-expression before 'unsigned'
     unsigned char* buf = Calloc(total_size, unsigned char);
                                             ^
video_io.cpp:34:58: error: 'Calloc' was not declared in this scope
     unsigned char* buf = Calloc(total_size, unsigned char);
                                                          ^
video_io.cpp:53:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for(int k = 0; k < bsize; k++)
                   ^
video_io.cpp:26:9: warning: unused variable 'ra' [-Wunused-variable]
     int ra = INTEGER(cimg_array)[0];
```

You can try devtools::build_win to test these things, or r-hub.

**Comment by seblamydlc** [comment]
I can't really test on windows but I think I found a fix. Do you know why the CI tests fail?

**Comment by dahtah** [comment]
I've just tested it again using devtools::build_win (you can too, right?). It looks like you've found the right fix, now it compiles. I've added an automated test as well. 
However: from the test results at [https://win-builder.r-project.org/KyzO7k49X6y6](), it looks like the test fails (not sure why yet), and in addition we're running into a stupid issue with the call to R_GetConnection. It looks like it mysteriously got dropped from the official R API: see [https://github.com/tidyverse/readr/issues/856](here)
We can email Jim Hester to see if there's any news, but it looks like the issue pops up in many packages. 
Ignore the CI tests, appveyor has never worked (should disable it) and travis is broken for some reason

**Comment by seblamydlc** [comment]
I don't have a windows machine though. The `R_GetConnection` thing is odd, if it's defined why aren't we able to use it. I also noticed that `load.video` on master returns an array which values are numeric between 0 and 1. I'll change the behavior of my function so it fits yours.

**Comment by dahtah** [comment]
Oh, didn't realise my advice about build_win was confusing: you don't need Windows to use it, it builds and tests remotely on a server. Also runs the full gamut of CRAN tests so it's quite useful. r-hub works the same. 
Will see if there's an update on R_GetConnection

**Comment by seblamydlc** [comment]
We could change the logic to use readBin instead maybe. Anyway I don't think we're in a huge rush to merge this feature. 
The logic of `save.video` could be improved in a very similar fashion. I'll get at it when I have time.

**Pull request merged**
