### PR TITLE
Remove plyr dependencies

### PR DESCRIPTION
**Pull request by srvanderplas**
[Issue 70](https://github.com/dahtah/imager/issues/70) discusses removing plyr from the dependency list. I have gone through the functions and removed plyr-based functions, replacing them with purrr where possible. In the case of plyr::rename, I have added the rename function code from plyr under the name rename_plyr - the functionality wasn't easily matched using the dplyr equivalent, but that one dependency doesn't justify importing the entire plyr package, so I did as suggested in Hadley's R Packages book and duplicated the function.

### CODE REVIEW

**Comment by dahtah** [comment]
Hi - thanks for doing this, it's really welcome. Why did you close the PR, though?

**Comment by srvanderplas** [comment]
I found another instance I'd missed and didn't have time to fix it just
then. I will try to get to it tomorrow 😊.

**Comment by srvanderplas** [comment]
Ok, Travis is passing now, so let me know if there's anything else that you need me to fix!

**Comment by Bisaloo** [comment]
Thanks a bunch @srvanderplas for your work on this and @dahtah for review and merging! This is awesome!

**Pull request merged**
