### PR TITLE
update logo

### PR DESCRIPTION
**Pull request by encaion**
how about this logo?

please accept this request if you like.

thanks

### CODE REVIEW

**Comment by dahtah** [comment]
Thanks for doing this, I like it! Maybe @ShotaOchi has an opinion? He's the maintainer now.

**Comment by ShotaOchi** [comment]
Cool logo.
I like it too.

**Comment by encaion** [comment]
@ShotaOchi 
Would you please help this problem?

"continuous-integration/appveyor/pr — AppVeyor build failed"

I have no idea for this msg.

**Comment by ShotaOchi** [comment]
> The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.

This message means appveyor doesn't know how to test the package because there is no appveyor.yml file.
The failure doesn't mean imager has a problem to be fixed.
We don't have to do something to fix the failure.

**Comment by encaion** [comment]
Great.

**Pull request closed without merging**
